### ISSUE TITLE
Proposal: Self detecting loading environment for bundles

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/stealjs#92] opened 2017-11-25 14:37 UTC
```js
( function( window, factory ) {
  'use strict';
  /* globals define: false, module: false, require: false */

  if ( typeof define == 'function' && define.amd ) {
    // AMD
    define( 'jquery-bridget/jquery-bridget',[ 'jquery' ], function( jQuery ) {
      factory( window, jQuery );
    });
  } else if ( typeof module == 'object' && module.exports ) {
    // CommonJS
    module.exports = factory(
      window,
      require('jquery')
    );
  } else {
    // browser global
    window.jQueryBridget = factory(
      window,
      window.jQuery
    );
  }

}( window, function factory( window, jQuery ) {
// return functtion execute function what so ever
})
```

**Comment by matthewp** [comment] 2017-11-27 13:27
Dupe of https://github.com/stealjs/rfcs/issues/4

**Closed by matthewp** 2017-11-27 13:27 UTC
